
name: Python Linting and Security

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort mypy bandit safety pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check code formatting with Black
      run: |
        black . --check
    - name: Check imports with isort
      run: |
        isort . --check
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
    - name: Type check with mypy
      run: |
        mypy . --ignore-missing-imports
    - name: Security check with bandit
      run: |
        bandit -r . -ll -ii -c bandit.yaml || exit 0
    - name: Dependency security check with safety
      run: |
        safety check || exit 0
    - name: Pylint check
      run: |
        pylint modules --disable=C0111,C0103 --exit-zero
