
name: Run Tests and Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly security scans

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov safety bandit
    - name: Test with pytest
      run: |
        pytest --cov=modules tests/ || exit 0
    - name: Run security scan with bandit
      run: |
        bandit -r modules/ -ll -ii -c bandit.yaml || exit 0
    - name: Check dependencies for security vulnerabilities
      run: |
        safety check || exit 0
    - name: Run static type checking
      run: |
        mypy modules/ || exit 0
    - name: Run code style checks
      run: |
        black --check modules/ || exit 0
        isort --check-only --profile black modules/ || exit 0
        flake8 modules/ || exit 0

  typescript-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test || exit 0
    - name: Run security scan
      run: |
        npx audit-ci --moderate || exit 0
        npx eslint . --ext .ts,.tsx || exit 0
    - name: Run TypeScript type checking
      run: |
        npm run typecheck || exit 0
    - name: Run ESLint
      run: |
        npm run lint || exit 0
        
  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate
